# Generated by Django 3.2.9 on 2021-11-08 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0007_alter_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('reference_code', models.CharField(max_length=10, null=True, unique=True, verbose_name='Reference code')),
                ('corporate_name', models.CharField(max_length=256, null=True, verbose_name='Corporate name')),
                ('fantasy_name', models.CharField(max_length=256, verbose_name='Fantasy name')),
                ('main_document', models.CharField(max_length=20, unique=True, verbose_name='CNPJ or CPF')),
                ('secondary_document', models.CharField(max_length=20, null=True, verbose_name='IE or RG')),
                ('is_corporate', models.BooleanField(default=True, verbose_name='Person or entity')),
                ('is_active', models.BooleanField(default=True, verbose_name='if client is active or not')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=256, verbose_name='Title of observation')),
                ('information', models.TextField(verbose_name='Information')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='File of observation')),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='client.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('zip_code', models.CharField(max_length=10, verbose_name='ZIP code of adress')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('complement', models.CharField(max_length=256, verbose_name='Complement of address')),
                ('number', models.CharField(max_length=10, verbose_name="'Number' of Address")),
                ('district', models.CharField(max_length=256, verbose_name='District of address')),
                ('city', models.CharField(max_length=256, verbose_name='City of address')),
                ('state', models.CharField(max_length=2, verbose_name='State of address')),
                ('is_main', models.BooleanField(default=True, verbose_name='Is the main address ? ')),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='client.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('telephone', models.CharField(max_length=15, verbose_name='telephone')),
                ('is_active', models.BooleanField(default=True, verbose_name='if client is active or not')),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='client.client', verbose_name='Client')),
            ],
            options={
                'unique_together': {('client', 'telephone')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('observation', models.CharField(max_length=256, verbose_name='Observation')),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='client.client', verbose_name='Client')),
                ('equipment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='settings.equipment', verbose_name='Equipment')),
            ],
            options={
                'unique_together': {('client', 'equipment')},
            },
        ),
    ]
