# Generated by Django 3.2.9 on 2021-11-06 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_user_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['label']},
        ),
    ]
