# Generated by Django 3.2.9 on 2021-11-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_setting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='label',
            field=models.CharField(max_length=255, unique=True, verbose_name='label of setting'),
        ),
    ]
