# Generated by Django 3.2.9 on 2021-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'INSERT'), (1, 'UPDATE'), (2, 'DELETE')], default=0, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
