# Generated by Django 3.2.9 on 2021-11-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(default='20211111184932679308', max_length=20, unique=True, verbose_name='Unique code'),
        ),
    ]
